// Generated by csdx stacksmith:import. Manual edits may be overwritten.


import { defineGlobalField, boolean, date, text } from "@timbenniks/contentstack-stacksmith";

export default defineGlobalField("seo", {
  title: "SEO",
  description: "It contains SEO related information.",
  fields: [
    text("meta_title", {
      metadata: {
        "default_value": "",
        "version": 3
      },
    }),
    text("meta_description", {
      metadata: {
        "default_value": "",
        "version": 3
      },
      multiline: true,
    }),
    text("keywords", {
      title: "Meta Keywords",
      metadata: {
        "default_value": "",
        "version": 3
      },
    }),
    boolean("enable_search_indexing", {
      metadata: {
        "default_value": true
      },
    }),
    date("date", {
      metadata: {
        "default_value": {}
      },
      startDate: null,
      endDate: null,
    }),
  ],
});
