// Generated by csdx stacksmith:import. Manual edits may be overwritten.


import { defineGlobalField, file, text } from "@timbenniks/contentstack-stacksmith";

export default defineGlobalField("testg", {
  title: "testg",
  fields: [
    text("single_line", {
      title: "Single Line Textbox",
      metadata: {
        "default_value": "",
        "version": 3
      },
    }),
    file("file"),
  ],
});
