// Generated by csdx stacksmith:import. Manual edits may be overwritten.


import { defineGlobalField, date, reference, text } from "@timbenniks/contentstack-stacksmith";

export default defineGlobalField("test_glooobal", {
  title: "test-glooobal",
  fields: [
    text("single_line", {
      title: "Single Line Textbox",
      metadata: {
        "default_value": ""
      },
    }),
    date("date", {
      metadata: {
        "default_value": {}
      },
      startDate: null,
      endDate: null,
    }),
    reference("reference", {
      metadata: {
        "ref_multiple": false
      },
      to: [
        "footer"
      ],
      refMultipleContentTypes: true,
    }),
  ],
});
