// Generated by csdx stacksmith:import. Manual edits may be overwritten.


import { defineModels } from "@timbenniks/contentstack-stacksmith";

import seo from "./global-fields/seo";
import test_glooobal from "./global-fields/test-glooobal";
import testg from "./global-fields/testg";
import author from "./content-types/author";
import blog_post from "./content-types/blog-post";
import footer from "./content-types/footer";
import header from "./content-types/header";
import page from "./content-types/page";
import test from "./content-types/test";

export default defineModels({
  contentTypes: [author, blog_post, footer, header, page, test],
  globalFields: [seo, test_glooobal, testg],
});
