// Generated by csdx stacksmith:import. Manual edits may be overwritten.


import { defineContentType, file, text } from "@timbenniks/contentstack-stacksmith";

export default defineContentType("author", {
  title: "Author",
  description: "It contains blog authors",
  fields: [
    text("title", {
      title: "Full Name",
      required: true,
      unique: true,
      metadata: {
        "_default": true,
        "version": 3
      },
    }),
    file("picture", {
      required: true,
      metadata: {
        "image": true
      },
    }),
    text("bio", {
      metadata: {
        "default_value": "",
        "version": 3
      },
      multiline: true,
    }),
  ],
  options: {
    "is_page": false,
    "singleton": false,
    "title": "title",
    "sub_title": []
  },
});
