// Generated by csdx stacksmith:import. Manual edits may be overwritten.


import { defineContentType, boolean, date, file, globalField, jsonRte, reference, text } from "@timbenniks/contentstack-stacksmith";

export default defineContentType("blog_post", {
  title: "Blog Entry",
  description: "It contains blog posts",
  fields: [
    text("title", {
      required: true,
      unique: true,
      metadata: {
        "_default": true,
        "version": 3
      },
    }),
    text("url", {
      title: "URL",
      metadata: {
        "_default": true,
        "version": 3
      },
    }),
    reference("author", {
      required: true,
      metadata: {
        "ref_multiple": false
      },
      to: [
        "author"
      ],
      refMultipleContentTypes: true,
    }),
    date("date", {
      description: "Optional field that overrides the publishing date.",
      metadata: {
        "default_value": {
          "custom": false,
          "date": "",
          "time": ""
        },
        "date_range": false
      },
      startDate: null,
      endDate: null,
    }),
    file("featured_image", {
      required: true,
      metadata: {
        "image": true
      },
    }),
    jsonRte("body", {
      metadata: {
        "embed_entry": false,
        "default_value": "",
        "options": []
      },
      referenceTo: [
        "sys_assets"
      ],
    }),
    reference("related_post", {
      metadata: {
        "ref_multiple": true
      },
      to: [
        "blog_post"
      ],
      refMultipleContentTypes: true,
    }),
    boolean("is_archived", {
      title: "Is Archived?",
      metadata: {
        "default_value": false
      },
    }),
    globalField("seo", {
      title: "SEO",
      ref: "seo",
    }),
    globalField("global_field", {
      title: "Global",
      ref: "test_glooobal",
    }),
  ],
  options: {
    "is_page": true,
    "singleton": false,
    "title": "title",
    "sub_title": [],
    "url_pattern": "/:title",
    "url_prefix": "/blog/"
  },
});
