// Generated by csdx stacksmith:import. Manual edits may be overwritten.


import { defineContentType, file, group, jsonRte, link, text } from "@timbenniks/contentstack-stacksmith";

export default defineContentType("footer", {
  title: "Footer",
  description: "It contains navigation, social media links and copyright text.",
  fields: [
    text("title", {
      required: true,
      unique: true,
      metadata: {
        "_default": true,
        "version": 3
      },
    }),
    file("logo", {
      required: true,
      metadata: {
        "image": true
      },
    }),
    group("navigation", {
      fields: [
        link("link", {
          multiple: true,
          metadata: {
            "default_value": {
              "title": "",
              "url": ""
            }
          },
        }),
      ],
    }),
    group("social", {
      fields: [
        group("social_share", {
          multiple: true,
          fields: [
            link("link", {
              metadata: {
                "default_value": "",
                "isTitle": true
              },
            }),
            file("icon", {
              required: true,
              metadata: {
                "image": true
              },
            }),
          ],
        }),
      ],
    }),
    jsonRte("copyright", {
      metadata: {
        "embed_entry": false,
        "default_value": "",
        "options": []
      },
      referenceTo: [
        "sys_assets"
      ],
    }),
  ],
  options: {
    "is_page": false,
    "singleton": true,
    "title": "title",
    "sub_title": []
  },
});
