// Generated by csdx stacksmith:import. Manual edits may be overwritten.


import { defineContentType, boolean, file, group, jsonRte, reference, text } from "@timbenniks/contentstack-stacksmith";

export default defineContentType("header", {
  title: "Header",
  description: "It contains the company logo, main navigation and notification bar.",
  fields: [
    text("title", {
      required: true,
      unique: true,
      metadata: {
        "_default": true,
        "version": 3
      },
    }),
    file("logo", {
      required: true,
      metadata: {
        "image": true
      },
    }),
    group("navigation_menu", {
      multiple: true,
      fields: [
        text("label", {
          description: "Overwrites the reference title if used",
          metadata: {
            "default_value": "",
            "isTitle": true,
            "version": 3
          },
        }),
        reference("page_reference", {
          required: true,
          metadata: {
            "ref_multiple": false
          },
          to: [
            "page"
          ],
          refMultipleContentTypes: true,
        }),
      ],
    }),
    group("notification_bar", {
      fields: [
        jsonRte("announcement_text", {
          metadata: {
            "embed_entry": false,
            "default_value": "",
            "options": []
          },
          referenceTo: [
            "sys_assets"
          ],
        }),
        boolean("show_announcement", {
          title: "Show Announcement?",
          metadata: {
            "default_value": false
          },
        }),
      ],
    }),
  ],
  options: {
    "is_page": false,
    "singleton": true,
    "title": "title",
    "sub_title": []
  },
});
