// Generated by csdx stacksmith:import. Manual edits may be overwritten.


import { defineContentType, enumField, file, globalField, group, jsonRte, link, modularBlocks, reference, text } from "@timbenniks/contentstack-stacksmith";

export default defineContentType("page", {
  title: "Page",
  description: "Re-usable content template that can be extended to fit many use cases. Example: Landing page, Contact page, About page, etc.",
  fields: [
    text("title", {
      required: true,
      unique: true,
      metadata: {
        "_default": true,
        "version": 3
      },
    }),
    text("url", {
      title: "URL",
      metadata: {
        "_default": true,
        "version": 3
      },
    }),
    modularBlocks("page_components", {
      blocks: [
        {
          uid: "hero_banner",
          title: "Hero Banner",
          fields: [
            file("banner_image", {
              metadata: {
                "image": true
              },
            }),
            text("bg_color", {
              title: "Bg color",
              metadata: {
                "version": 3
              },
              extensionUid: "bltf786e59112341d08",
              config: {},
            }),
            text("banner_title", {
              metadata: {
                "default_value": "",
                "version": 3
              },
            }),
            text("banner_description", {
              metadata: {
                "default_value": "",
                "version": 3
              },
              multiline: true,
            }),
            link("call_to_action", {
              title: "Call to Action",
              metadata: {
                "default_value": {
                  "title": "",
                  "url": ""
                }
              },
            }),
          ],
        },
        {
          uid: "contact_details",
          title: "Contact Details",
          fields: [
            text("address", {
              metadata: {
                "default_value": "",
                "version": 3
              },
              multiline: true,
            }),
            text("phone", {
              metadata: {
                "default_value": "",
                "version": 3
              },
            }),
            text("email", {
              metadata: {
                "default_value": "",
                "version": 3
              },
            }),
          ],
        },
        {
          uid: "section_with_buckets",
          title: "Section with Buckets",
          fields: [
            text("title_h2", {
              metadata: {
                "default_value": "",
                "version": 3
              },
            }),
            text("description", {
              metadata: {
                "default_value": "",
                "version": 3
              },
              multiline: true,
            }),
            group("buckets", {
              multiple: true,
              fields: [
                text("title_h3", {
                  metadata: {
                    "default_value": "",
                    "isTitle": true,
                    "version": 3
                  },
                }),
                jsonRte("description", {
                  metadata: {
                    "embed_entry": false,
                    "default_value": "",
                    "options": []
                  },
                  referenceTo: [
                    "sys_assets"
                  ],
                }),
                file("icon", {
                  required: true,
                  metadata: {
                    "image": true
                  },
                }),
                link("call_to_action", {
                  title: "Call to Action",
                  metadata: {
                    "default_value": {
                      "title": "",
                      "url": ""
                    }
                  },
                }),
              ],
            }),
          ],
        },
        {
          uid: "section",
          title: "Section",
          fields: [
            text("title_h2", {
              metadata: {
                "default_value": "",
                "version": 3
              },
            }),
            text("description", {
              metadata: {
                "default_value": "",
                "version": 3
              },
              multiline: true,
            }),
            link("call_to_action", {
              title: "Call to Action",
              metadata: {
                "default_value": {
                  "title": "",
                  "url": ""
                }
              },
            }),
            file("image", {
              required: true,
              metadata: {
                "image": true
              },
            }),
            enumField("image_alignment", {
              metadata: {
                "default_value": "Left",
                "version": 3
              },
              choices: [
                "Left",
                "Right"
              ],
              displayType: "radio",
            }),
          ],
        },
        {
          uid: "section_with_cards",
          title: "Section with Cards",
          fields: [
            group("cards", {
              multiple: true,
              fields: [
                text("title_h3", {
                  metadata: {
                    "default_value": "",
                    "isTitle": true,
                    "version": 3
                  },
                }),
                text("description", {
                  metadata: {
                    "default_value": "",
                    "version": 3
                  },
                  multiline: true,
                }),
                link("call_to_action", {
                  title: "Call to Action",
                  metadata: {
                    "default_value": {
                      "title": "",
                      "url": ""
                    }
                  },
                }),
              ],
            }),
          ],
        },
        {
          uid: "section_with_html_code",
          title: "Section with HTML Code",
          fields: [
            text("title", {
              metadata: {
                "default_value": "",
                "version": 3
              },
            }),
            jsonRte("description", {
              metadata: {
                "embed_entry": false,
                "default_value": "",
                "options": []
              },
              referenceTo: [
                "sys_assets"
              ],
            }),
            text("html_code", {
              title: "HTML Code",
              metadata: {
                "version": 3
              },
              extensionUid: "blt1513a7c8ac603455",
              config: {},
            }),
            enumField("html_code_alignment", {
              title: "HTML Code Alignment",
              metadata: {
                "default_value": "Left",
                "instruction": "Choose which side your HTML code should be rendered.",
                "version": 3
              },
              choices: [
                "Left",
                "Right"
              ],
              displayType: "radio",
            }),
          ],
        },
        {
          uid: "from_blog",
          title: "From Blog",
          fields: [
            text("title_h2", {
              metadata: {
                "default_value": "",
                "version": 3
              },
            }),
            reference("featured_blogs", {
              metadata: {
                "ref_multiple": true
              },
              to: [
                "blog_post"
              ],
              refMultipleContentTypes: true,
            }),
            link("view_articles", {
              metadata: {
                "default_value": {
                  "title": "",
                  "url": ""
                }
              },
            }),
          ],
        },
        {
          uid: "our_team",
          title: "Our Team",
          fields: [
            text("title_h2", {
              metadata: {
                "default_value": "",
                "version": 3
              },
            }),
            text("description", {
              metadata: {
                "default_value": "",
                "version": 3
              },
              multiline: true,
            }),
            group("employees", {
              multiple: true,
              fields: [
                text("name", {
                  metadata: {
                    "default_value": "",
                    "isTitle": true,
                    "version": 3
                  },
                }),
                text("designation", {
                  metadata: {
                    "default_value": "",
                    "version": 3
                  },
                }),
                file("image", {
                  required: true,
                  metadata: {
                    "image": true
                  },
                }),
              ],
            }),
          ],
        },
        {
          uid: "widget",
          title: "Widget",
          fields: [
            text("title_h2", {
              metadata: {
                "default_value": "",
                "version": 3
              },
            }),
            enumField("type", {
              metadata: {
                "default_value": "",
                "version": 3
              },
              choices: [
                "Blog Archive",
                "Related Posts"
              ],
              displayType: "dropdown",
            }),
          ],
        },
      ],
    }),
    globalField("seo", {
      title: "SEO",
      ref: "seo",
    }),
  ],
  options: {
    "is_page": true,
    "singleton": false,
    "title": "title",
    "sub_title": [],
    "url_pattern": "/:title",
    "url_prefix": "/"
  },
});
