// Generated by csdx stacksmith:import. Manual edits may be overwritten.


import { defineContentType, date, globalField, jsonRte, number, richText, text } from "@timbenniks/contentstack-stacksmith";

export default defineContentType("test", {
  title: "test",
  fields: [
    text("title", {
      required: true,
      unique: true,
      metadata: {
        "_default": true,
        "version": 3
      },
    }),
    date("date", {
      metadata: {
        "default_value": {}
      },
      startDate: null,
      endDate: null,
    }),
    text("custom", {
      extensionUid: "bltf786e59112341d08",
      config: {},
    }),
    number("custom2", {
      extensionUid: "blta661d7cf7fcd396f",
      config: {},
    }),
    globalField("global_field", {
      title: "Global",
      ref: "testg",
    }),
    jsonRte("json_rte", {
      title: "JSON Rich Text Editor",
      required: true,
      multiple: true,
      metadata: {
        "embed_entry": true,
        "default_value": "",
        "options": [],
        "isTitle": false
      },
      referenceTo: [
        "author",
        "sys_assets"
      ],
    }),
    richText("rich_text_editor", {
      required: true,
      multiple: true,
      metadata: {
        "options": [],
        "isTitle": false,
        "version": 3
      },
    }),
  ],
  options: {
    "is_page": false,
    "singleton": false,
    "sub_title": [],
    "title": "title"
  },
});
